name: Regression Suite

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: reports/


    '''
    Think of regression.yml as:

📋  Instructions for GitHub Actions telling GitHub:
    Whenever code changes happen, automatically run my automation tests.

    Artifacts =
👉 downloadable files after pipeline completes

  Example:

  HTML reports
  screenshots
  logs

  Your regression.yml is basically:

👉 “automation instructions for GitHub cloud machines.”

  The regression.yml file defines the CI/CD workflow for the automation framework using GitHub Actions. 
  It automatically triggers test execution whenever code is pushed or a pull request is created on the main branch. 
  The workflow provisions a Linux runner(UBUNTU VM), installs Python and project dependencies, downloads your repository code into the VM
  executes the pytest regression suite, and uploads the generated test reports as artifacts for analysis.

    End-to-End Flow

When you push code:

Developer Pushes Code
        ↓
GitHub Actions Triggered
        ↓
Ubuntu VM Created
        ↓
Repo Downloaded
        ↓
Python Installed
        ↓
Dependencies Installed
        ↓
Pytest Runs
        ↓
Reports Generated
        ↓
Artifacts Uploaded

Now you need to verify:
👉 “Does the pipeline actually run successfully in GitHub?”

As soon as push completes:

👉 GitHub detects:

.github/workflows/regression.yml

and automatically triggers pipeline.
    '''